// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_tdo8dVVpSYSGpx2lo4cfBOGQR6Ok2ns',
    appId: '1:855349177144:web:403cfa7bd3e0bd151eefcd',
    messagingSenderId: '855349177144',
    projectId: 'camseltry',
    authDomain: 'camseltry.firebaseapp.com',
    storageBucket: 'camseltry.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyrMmNY3IJZwEf-kO2TtEeWWdm05oaGL8',
    appId: '1:855349177144:android:95ba4dbf73ee6c301eefcd',
    messagingSenderId: '855349177144',
    projectId: 'camseltry',
    storageBucket: 'camseltry.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKfb22XFFk-xuf3zH5YNZrkgt8alAF4fg',
    appId: '1:855349177144:ios:8ebee09193f3521d1eefcd',
    messagingSenderId: '855349177144',
    projectId: 'camseltry',
    storageBucket: 'camseltry.appspot.com',
    iosBundleId: 'com.example.campusSell',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKfb22XFFk-xuf3zH5YNZrkgt8alAF4fg',
    appId: '1:855349177144:ios:8ebee09193f3521d1eefcd',
    messagingSenderId: '855349177144',
    projectId: 'camseltry',
    storageBucket: 'camseltry.appspot.com',
    iosBundleId: 'com.example.campusSell',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_tdo8dVVpSYSGpx2lo4cfBOGQR6Ok2ns',
    appId: '1:855349177144:web:a0d570862f714edd1eefcd',
    messagingSenderId: '855349177144',
    projectId: 'camseltry',
    authDomain: 'camseltry.firebaseapp.com',
    storageBucket: 'camseltry.appspot.com',
  );

}